plugins {
    id 'java-library'
    id 'maven-publish'
}

// 禁用所有 Java 编译
java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

jar.enabled = false

def aarFile = file('SdkApiJar_V1.250915.0914.aar')
if (!aarFile.exists()) {
    throw new GradleException("AAR not found!")
}

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = 'SdkApiJar'
            groupId = 'com.github.SUNTEK-DEV'
            version = project.version

            artifact(aarFile) {
                extension 'aar'
                classifier '' // 确保没有 classifier
            }

            pom {
                packaging = 'aar' // 关键！告诉消费者这是 AAR
                name = 'SdkApiJar'
                description = 'Prebuilt AAR'
            }
        }
    }
}